language: go

go:
  - 1.8
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip
#install:
#  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#  - go get -v github.com/mattn/goveralls
script:
  - make test